spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/finalproject__test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: "!junki123"
  jpa:
    hibernate:
      ddl-auto: create
